FROM alpine:3.15.0
LABEL version = "alpine:3.15.0" maintainer="radouane" os="Linux"
ENV CONTAINER_USER="radouane"
RUN adduser -S $CONTAINER_USER
CMD ["echo", "hello-alpine, I’m Radouane and this is a container from my first image"]
